include config.sh

init-heroku:
	heroku config:add TZ="America/Los_Angeles"

	heroku config:add \
		HEROKU_URL=$(HEROKU_URL) \
	 	HUBOT_LOG_LEVEL=$(HUBOT_LOG_LEVEL) \
		HUBOT_OFF_THE_GRID_LOCATION_ID=$(HUBOT_OFF_THE_GRID_LOCATION_ID) \
	 	HUBOT_SLACK_BOTNAME=$(HUBOT_SLACK_BOTNAME) \
		HUBOT_SLACK_CHANNELMODE=$(HUBOT_SLACK_CHANNELMODE) \
		HUBOT_SLACK_CHANNELS=$(HUBOT_SLACK_CHANNELS) \
		HUBOT_SLACK_TEAM=$(HUBOT_SLACK_TEAM) \
		HUBOT_SLACK_TOKEN=$(HUBOT_SLACK_TOKEN) \
		HUBOT_SOUNDSPACES_ROOM_KEY=$(HUBOT_SOUNDSPACES_ROOM_KEY) \
		HUBOT_SOUNDSPACES_BASE_SOUND_URL=$(HUBOT_SOUNDSPACES_BASE_SOUND_URL) \
		HUBOT_SOUNDSPACES_SOUND_URL=$(HUBOT_SOUNDSPACES_SOUND_URL) \
		MONGOLAB_URI=$(MONGOLAB_URI)
